### ISSUE TITLE
daysToCurrentEpochFromConverterEpoch is not a member of ace_time::Epoch

### ISSUE THREAD

**Issue by chrish987** [bxparks/AceTimeClock#21]
I have a compile issue with AceTimeClock 1.2.4 and AceTime 2.2.3.

` 
NtpClock.cpp: 182:14: error: 'daysToCurrentEpochFromConverterEpoch' is not a member of 'ace_time::Epoch
       Epoch*: daysToCurrentEpochFromConverterEpoch()
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

I am guessing the issue is the renamed method daysToCurrentEpochFromConverterEpoch() to daysToCurrentEpochFromInternalEpoch() in AceTime 2.2.3. AceTime 2.2.2 works ok.

**Comment by bxparks** [comment]
The fix is committed into `develop`, but for some reason, I never created a new release. I will do that shortly...

**Comment by chrish987** [comment]
thanks for quick response.

**Comment by bxparks** [comment]
Released v1.3.0.
It should get picked up by the Arduino Library Manager in the next day or two.
You also need to upgrade to AceTime v2.3.0.
Please reopen or create a new ticket if you encounter problems.
